.php_test: &phptest
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer run style
    - composer run test

before_script:
  - apk update
  - apk add zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - php -r "unlink('composer-setup.php');"

php-7.1:
  image: php:7.3-alpine
  <<: *phptest

php-7.2:
  image: php:7.3-alpine
  <<: *phptest

php-7.3:
  image: php:7.3-alpine
  <<: *phptest

php-7.4:
  image: php:7.4-alpine
  <<: *phptest

php-8:
  image: php:8-alpine
  <<: *phptest
