.php_test: &phptest
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer run test

php-7.1:
  image: php:7.3
  <<: *phptest

php-7.2:
  image: php:7.3
  <<: *phptest

php-7.3:
  image: php:7.3
  <<: *phptest

php-7.4:
  image: php:7.4
  <<: *phptest

php-8:
  image: php:8
  <<: *phptest
