language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
before_script:
  - composer remove phpunit/phpunit && composer require --dev phpunit/phpunit:^5 --update-with-dependencies
  - composer install
script:
  - composer run test